//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: shared_song.proto

package igrek.songbook.custom.share.protos;

@kotlin.jvm.JvmSynthetic
inline fun sharedSongDto(block: igrek.songbook.custom.share.protos.SharedSongDtoKt.Dsl.() -> Unit): SharedSong.SharedSongDto =
  igrek.songbook.custom.share.protos.SharedSongDtoKt.Dsl._create(SharedSong.SharedSongDto.newBuilder())
    .apply { block() }._build()

object SharedSongDtoKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  class Dsl private constructor(
    @kotlin.jvm.JvmField private val _builder: SharedSong.SharedSongDto.Builder
  ) {
    companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: SharedSong.SharedSongDto.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): SharedSong.SharedSongDto = _builder.build()

    /**
     * <code>string title = 1;</code>
     */
    var title: kotlin.String
      @JvmName("getTitle")
      get() = _builder.getTitle()
      @JvmName("setTitle")
      set(value) {
        _builder.setTitle(value)
      }

    /**
     * <code>string title = 1;</code>
     */
    fun clearTitle() {
      _builder.clearTitle()
    }

    /**
     * <code>string content = 2;</code>
     */
    var content: kotlin.String
      @JvmName("getContent")
      get() = _builder.getContent()
      @JvmName("setContent")
      set(value) {
        _builder.setContent(value)
      }

    /**
     * <code>string content = 2;</code>
     */
    fun clearContent() {
      _builder.clearContent()
    }

    /**
     * <code>optional string customCategory = 3;</code>
     */
    var customCategory: kotlin.String
      @JvmName("getCustomCategory")
      get() = _builder.getCustomCategory()
      @JvmName("setCustomCategory")
      set(value) {
        _builder.setCustomCategory(value)
      }

    /**
     * <code>optional string customCategory = 3;</code>
     */
    fun clearCustomCategory() {
      _builder.clearCustomCategory()
    }

    /**
     * <code>optional string customCategory = 3;</code>
     * @return Whether the customCategory field is set.
     */
    fun hasCustomCategory(): kotlin.Boolean {
      return _builder.hasCustomCategory()
    }

    /**
     * <code>optional int64 chordsNotation = 4;</code>
     */
    var chordsNotation: kotlin.Long
      @JvmName("getChordsNotation")
      get() = _builder.getChordsNotation()
      @JvmName("setChordsNotation")
      set(value) {
        _builder.setChordsNotation(value)
      }

    /**
     * <code>optional int64 chordsNotation = 4;</code>
     */
    fun clearChordsNotation() {
      _builder.clearChordsNotation()
    }

    /**
     * <code>optional int64 chordsNotation = 4;</code>
     * @return Whether the chordsNotation field is set.
     */
    fun hasChordsNotation(): kotlin.Boolean {
      return _builder.hasChordsNotation()
    }
  }
}

@kotlin.jvm.JvmSynthetic
inline fun SharedSong.SharedSongDto.copy(block: igrek.songbook.custom.share.protos.SharedSongDtoKt.Dsl.() -> Unit): SharedSong.SharedSongDto =
  igrek.songbook.custom.share.protos.SharedSongDtoKt.Dsl._create(this.toBuilder()).apply { block() }
    ._build()
